# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'course_work_ui.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(777, 576)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(777, 576))
        Dialog.setMaximumSize(QtCore.QSize(777, 576))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        Dialog.setFont(font)
        Dialog.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"\n"
"")
        self.add_row = QtWidgets.QPushButton(Dialog)
        self.add_row.setGeometry(QtCore.QRect(60, 200, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_row.sizePolicy().hasHeightForWidth())
        self.add_row.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.add_row.setFont(font)
        self.add_row.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_row.setMouseTracking(True)
        self.add_row.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(235, 235, 235);\n"
"border: 0.5px solid #6a6a6a;\n"
"border-bottom: 2px solid #6a6a6a;\n"
"border-right: 2px solid #6a6a6a;")
        self.add_row.setCheckable(False)
        self.add_row.setAutoDefault(False)
        self.add_row.setDefault(False)
        self.add_row.setFlat(True)
        self.add_row.setObjectName("add_row")
        self.exit_table = QtWidgets.QPushButton(Dialog)
        self.exit_table.setEnabled(True)
        self.exit_table.setGeometry(QtCore.QRect(60, 160, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit_table.sizePolicy().hasHeightForWidth())
        self.exit_table.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.exit_table.setFont(font)
        self.exit_table.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit_table.setMouseTracking(True)
        self.exit_table.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(235, 235, 235);\n"
"border: 0.5px solid #6a6a6a;\n"
"border-bottom: 2px solid #6a6a6a;\n"
"border-right: 2px solid #6a6a6a;")
        self.exit_table.setCheckable(False)
        self.exit_table.setAutoDefault(False)
        self.exit_table.setDefault(False)
        self.exit_table.setFlat(True)
        self.exit_table.setObjectName("exit_table")
        self.table_widget = QtWidgets.QTableWidget(Dialog)
        self.table_widget.setGeometry(QtCore.QRect(219, 27, 541, 535))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_widget.sizePolicy().hasHeightForWidth())
        self.table_widget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.table_widget.setFont(font)
        self.table_widget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.table_widget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.table_widget.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"gridline: 1px solid #6a6a6a;")
        self.table_widget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.table_widget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.table_widget.setLineWidth(0)
        self.table_widget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.table_widget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.table_widget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table_widget.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.table_widget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.table_widget.setGridStyle(QtCore.Qt.SolidLine)
        self.table_widget.setObjectName("table_widget")
        self.table_widget.setColumnCount(0)
        self.table_widget.setRowCount(0)
        self.edit_table = QtWidgets.QPushButton(Dialog)
        self.edit_table.setEnabled(True)
        self.edit_table.setGeometry(QtCore.QRect(60, 160, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_table.sizePolicy().hasHeightForWidth())
        self.edit_table.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.edit_table.setFont(font)
        self.edit_table.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.edit_table.setMouseTracking(True)
        self.edit_table.setToolTip("")
        self.edit_table.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(235, 235, 235);\n"
"border: 0.5px solid #6a6a6a;\n"
"border-bottom: 2px solid #6a6a6a;\n"
"border-right: 2px solid #6a6a6a;")
        self.edit_table.setCheckable(False)
        self.edit_table.setAutoDefault(False)
        self.edit_table.setDefault(False)
        self.edit_table.setFlat(True)
        self.edit_table.setObjectName("edit_table")
        self.change_row = QtWidgets.QPushButton(Dialog)
        self.change_row.setGeometry(QtCore.QRect(60, 240, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.change_row.sizePolicy().hasHeightForWidth())
        self.change_row.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.change_row.setFont(font)
        self.change_row.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.change_row.setMouseTracking(True)
        self.change_row.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(235, 235, 235);\n"
"border: 0.5px solid #6a6a6a;\n"
"border-bottom: 2px solid #6a6a6a;\n"
"border-right: 2px solid #6a6a6a;")
        self.change_row.setCheckable(False)
        self.change_row.setAutoDefault(False)
        self.change_row.setDefault(False)
        self.change_row.setFlat(True)
        self.change_row.setObjectName("change_row")
        self.delete_row = QtWidgets.QPushButton(Dialog)
        self.delete_row.setGeometry(QtCore.QRect(60, 280, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_row.sizePolicy().hasHeightForWidth())
        self.delete_row.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.delete_row.setFont(font)
        self.delete_row.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_row.setMouseTracking(True)
        self.delete_row.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(235, 235, 235);\n"
"border: 0.5px solid #6a6a6a;\n"
"border-bottom: 2px solid #6a6a6a;\n"
"border-right: 2px solid #6a6a6a;")
        self.delete_row.setCheckable(False)
        self.delete_row.setAutoDefault(False)
        self.delete_row.setDefault(False)
        self.delete_row.setFlat(True)
        self.delete_row.setObjectName("delete_row")
        self.add_cols = QtWidgets.QPushButton(Dialog)
        self.add_cols.setGeometry(QtCore.QRect(60, 200, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_cols.sizePolicy().hasHeightForWidth())
        self.add_cols.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.add_cols.setFont(font)
        self.add_cols.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_cols.setMouseTracking(True)
        self.add_cols.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(235, 235, 235);\n"
"border: 0.5px solid #6a6a6a;\n"
"border-bottom: 2px solid #6a6a6a;\n"
"border-right: 2px solid #6a6a6a;")
        self.add_cols.setCheckable(False)
        self.add_cols.setAutoDefault(False)
        self.add_cols.setDefault(False)
        self.add_cols.setFlat(True)
        self.add_cols.setObjectName("add_cols")
        self.num_of_columns = QtWidgets.QPushButton(Dialog)
        self.num_of_columns.setGeometry(QtCore.QRect(60, 200, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_of_columns.sizePolicy().hasHeightForWidth())
        self.num_of_columns.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.num_of_columns.setFont(font)
        self.num_of_columns.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.num_of_columns.setMouseTracking(True)
        self.num_of_columns.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(235, 235, 235);\n"
"border: 0.5px solid #6a6a6a;\n"
"border-bottom: 2px solid #6a6a6a;\n"
"border-right: 2px solid #6a6a6a;")
        self.num_of_columns.setCheckable(False)
        self.num_of_columns.setAutoDefault(False)
        self.num_of_columns.setDefault(False)
        self.num_of_columns.setFlat(True)
        self.num_of_columns.setObjectName("num_of_columns")
        self.delete_col_names = QtWidgets.QPushButton(Dialog)
        self.delete_col_names.setGeometry(QtCore.QRect(60, 320, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_col_names.sizePolicy().hasHeightForWidth())
        self.delete_col_names.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.delete_col_names.setFont(font)
        self.delete_col_names.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_col_names.setMouseTracking(True)
        self.delete_col_names.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(235, 235, 235);\n"
"border: 0.5px solid #6a6a6a;\n"
"border-bottom: 2px solid #6a6a6a;\n"
"border-right: 2px solid #6a6a6a;")
        self.delete_col_names.setCheckable(False)
        self.delete_col_names.setAutoDefault(False)
        self.delete_col_names.setDefault(False)
        self.delete_col_names.setFlat(True)
        self.delete_col_names.setObjectName("delete_col_names")
        self.new_table = QtWidgets.QPushButton(Dialog)
        self.new_table.setEnabled(True)
        self.new_table.setGeometry(QtCore.QRect(60, 200, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_table.sizePolicy().hasHeightForWidth())
        self.new_table.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.new_table.setFont(font)
        self.new_table.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.new_table.setMouseTracking(True)
        self.new_table.setToolTip("")
        self.new_table.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(235, 235, 235);\n"
"border: 0.5px solid #6a6a6a;\n"
"border-bottom: 2px solid #6a6a6a;\n"
"border-right: 2px solid #6a6a6a;")
        self.new_table.setCheckable(False)
        self.new_table.setAutoDefault(False)
        self.new_table.setDefault(False)
        self.new_table.setFlat(True)
        self.new_table.setObjectName("new_table")
        self.add_table = QtWidgets.QPushButton(Dialog)
        self.add_table.setEnabled(True)
        self.add_table.setGeometry(QtCore.QRect(60, 200, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_table.sizePolicy().hasHeightForWidth())
        self.add_table.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.add_table.setFont(font)
        self.add_table.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_table.setMouseTracking(True)
        self.add_table.setToolTip("")
        self.add_table.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(235, 235, 235);\n"
"border: 0.5px solid #6a6a6a;\n"
"border-bottom: 2px solid #6a6a6a;\n"
"border-right: 2px solid #6a6a6a;")
        self.add_table.setCheckable(False)
        self.add_table.setAutoDefault(False)
        self.add_table.setDefault(False)
        self.add_table.setFlat(True)
        self.add_table.setObjectName("add_table")
        self.delete_table = QtWidgets.QPushButton(Dialog)
        self.delete_table.setEnabled(True)
        self.delete_table.setGeometry(QtCore.QRect(60, 240, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_table.sizePolicy().hasHeightForWidth())
        self.delete_table.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.delete_table.setFont(font)
        self.delete_table.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_table.setMouseTracking(True)
        self.delete_table.setToolTip("")
        self.delete_table.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(235, 235, 235);\n"
"border: 0.5px solid #6a6a6a;\n"
"border-bottom: 2px solid #6a6a6a;\n"
"border-right: 2px solid #6a6a6a;")
        self.delete_table.setCheckable(False)
        self.delete_table.setAutoDefault(False)
        self.delete_table.setDefault(False)
        self.delete_table.setFlat(True)
        self.delete_table.setObjectName("delete_table")
        self.close_database = QtWidgets.QPushButton(Dialog)
        self.close_database.setGeometry(QtCore.QRect(223, 5, 41, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_database.sizePolicy().hasHeightForWidth())
        self.close_database.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.close_database.setFont(font)
        self.close_database.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close_database.setStyleSheet("border-radius: 2px;\n"
"background-color: rgb(235, 235, 235);\n"
"border: 0.5px solid rgba(0,0,0,0);")
        self.close_database.setDefault(False)
        self.close_database.setFlat(False)
        self.close_database.setObjectName("close_database")
        self.open_xml = QtWidgets.QPushButton(Dialog)
        self.open_xml.setGeometry(QtCore.QRect(13, 5, 61, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_xml.sizePolicy().hasHeightForWidth())
        self.open_xml.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.open_xml.setFont(font)
        self.open_xml.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_xml.setStyleSheet("border-radius: 2px;\n"
"background-color: rgb(235, 235, 235);\n"
"border: 0.5px solid rgba(0,0,0,0);")
        self.open_xml.setDefault(False)
        self.open_xml.setFlat(False)
        self.open_xml.setObjectName("open_xml")
        self.save_as = QtWidgets.QPushButton(Dialog)
        self.save_as.setGeometry(QtCore.QRect(148, 5, 61, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_as.sizePolicy().hasHeightForWidth())
        self.save_as.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.save_as.setFont(font)
        self.save_as.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save_as.setStyleSheet("border-radius: 2px;\n"
"background-color: rgb(235, 235, 235);\n"
"border: 0.5px solid rgba(0,0,0,0);")
        self.save_as.setDefault(False)
        self.save_as.setFlat(False)
        self.save_as.setObjectName("save_as")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(7, 2, 764, 1))
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(7, 570, 764, 1))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(6, 1, 1, 571))
        self.line_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_3.setLineWidth(1)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setGeometry(QtCore.QRect(770, 1, 1, 571))
        self.line_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_4.setLineWidth(1)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(Dialog)
        self.line_5.setGeometry(QtCore.QRect(7, 22, 764, 1))
        self.line_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_5.setLineWidth(1)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(Dialog)
        self.line_6.setGeometry(QtCore.QRect(80, 3, 1, 20))
        self.line_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(Dialog)
        self.line_7.setGeometry(QtCore.QRect(214, 3, 1, 20))
        self.line_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(Dialog)
        self.line_8.setGeometry(QtCore.QRect(273, 3, 1, 20))
        self.line_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setObjectName("line_8")
        self.create_database = QtWidgets.QPushButton(Dialog)
        self.create_database.setGeometry(QtCore.QRect(87, 5, 51, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_database.sizePolicy().hasHeightForWidth())
        self.create_database.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.create_database.setFont(font)
        self.create_database.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.create_database.setStyleSheet("border-radius: 2px;\n"
"background-color: rgb(235, 235, 235);\n"
"border: 0.5px solid rgba(0,0,0,0);")
        self.create_database.setDefault(False)
        self.create_database.setFlat(False)
        self.create_database.setObjectName("create_database")
        self.line_9 = QtWidgets.QFrame(Dialog)
        self.line_9.setGeometry(QtCore.QRect(142, 3, 1, 20))
        self.line_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setObjectName("line_9")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "DbManager"))
        self.add_row.setText(_translate("Dialog", "Insert"))
        self.exit_table.setText(_translate("Dialog", "Leave table"))
        self.table_widget.setSortingEnabled(True)
        self.edit_table.setText(_translate("Dialog", "Edit table"))
        self.change_row.setText(_translate("Dialog", "Save changes"))
        self.delete_row.setText(_translate("Dialog", "Delete row"))
        self.add_cols.setText(_translate("Dialog", "Insert columns"))
        self.num_of_columns.setText(_translate("Dialog", "Enter"))
        self.delete_col_names.setText(_translate("Dialog", "Delete columns"))
        self.new_table.setText(_translate("Dialog", "New table"))
        self.add_table.setText(_translate("Dialog", "Add table"))
        self.delete_table.setText(_translate("Dialog", "Delete table"))
        self.close_database.setText(_translate("Dialog", "Close"))
        self.open_xml.setText(_translate("Dialog", "Open..."))
        self.save_as.setText(_translate("Dialog", "Save as..."))
        self.create_database.setText(_translate("Dialog", "Create"))

